[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 2_000

[rpc_endpoints]
# have to add chainId comment at the end of each line for deploy.py to work
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}" # 1
goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}" # 5
optimism = "https://optimism-mainnet.infura.io/v3/${INFURA_API_KEY}" # 10
optimism-goerli = "https://optimism-goerli.infura.io/v3/${INFURA_API_KEY}" # 420
arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}" # 42161
arbitrum-goerli = "https://arbitrum-goerli.infura.io/v3/${INFURA_API_KEY}"
polygon = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}" # 137 # legacy
polygon-mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}" # 80001 # legacy
polygon-zkevm = "https://zkevm-rpc.com" # 1101
polygon-zkevm-testnet = "https://rpc.public.zkevm-test.net"  # 1442
mantle = "https://rpc.mantle.xyz/" # 5000 # legacy
mantle-testnet = "https://rpc.testnet.mantle.xyz/" # 5001 # legacy
gnosis = "https://rpc.gnosis.pm" # 100
gnosis-testnet = "https://rpc.chiadochain.net" # 10200
filecoin = "https://rpc.ankr.com/filecoin" # 314
filecoin-testnet = "https://filecoin-calibration.chainstacklabs.com/rpc/v1" # 314159
zksync = "https://mainnet.era.zksync.io" # 324
zksync-testnet = "https://testnet.era.zksync.dev" # 280
base = "https://developer-access-mainnet.base.org" # 8453
base-testnet = "https://goerli.base.org" # 84531
milkomeda-c1 = "https://rpc-mainnet-cardano-evm.c1.milkomeda.com" # 2001 # legacy
milkomeda-c1-testnet = "https://rpc-devnet-cardano-evm.c1.milkomeda.com	" # 200101 # legacy
# palm = "https://palm-mainnet.infura.io/v3/${INFURA_API_KEY}"
# palm-testnet = "https://palm-testnet.infura.io/v3/${INFURA_API_KEY}"
# avalanche = "https://avalanche-mainnet.infura.io/v3/${INFURA_API_KEY}"
# near = "https://near-mainnet.infura.io/v3/${INFURA_API_KEY}"
# aurora = "https://aurora-mainnet.infura.io/v3/${INFURA_API_KEY}"
# starknet = "https://starknet-mainnet.infura.io/v3/${INFURA_API_KEY}"
# starket-goerli = "https://starknet-goerli.infura.io/v3/${INFURA_API_KEY}"
# celo = "https://celo-mainnet.infura.io/v3/${INFURA_API_KEY}"
# celo-alfajores = "https://celo-alfajores.infura.io/v3/${INFURA_API_KEY}" # 44787
# moonbase = "https://rpc.api.moonbase.moonbeam.network"
# moonbeam = "https://rpc.api.moobeam.network"
# zetachain-testnet = "https://zetachain-athens-evm.blockpi.network/v1/rpc/public" # 7001
# zetachain = "https://api.mainnet.zetachain.com/evm" # 7000
# neon = "https://neon-mainnet.everstake.one" # 245022934 # legacy
# neon-devnet = "https://devnet.neonevm.org" # 245022926 # legacy


[etherscan]
mainnet = { key = "${ETHERSCAN_TOKEN}" }
goerli = { key = "${ETHERSCAN_TOKEN}" }
polygon = { key = "${POLYGONSCAN_TOKEN}" }
polygon-mumbai = { key = "${POLYGONSCAN_TOKEN}" }
optimism = { key = "${OPTISCAN_TOKEN}" }
optimism-goerli = { key = "${OPTISCAN_TOKEN}" }
arbitrum = { key = "${ARBISCAN_TOKEN}" }
polygon-zkevm-testnet = { key = "${POLYGOSCAN_ZKEVM_TOKEN}" }
base = { key = "${BASESCAN_TOKEN}", url = "https://api.basescan.org" }
base-testnet = { key = "${BASESCAN_TOKEN}", url = "https://api-goerli.basescan.org" }
# unknownchain = { key = "ABCDEFG", url = "https://<etherscan-api-url-for-that-chain>" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
