[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 2000

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
optimism = "https://optimism-mainnet.infura.io/v3/${INFURA_API_KEY}"
optimism-goerli = "https://optimism-goerli.infura.io/v3/${INFURA_API_KEY}"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}"
polygon = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}" # 137 # legacy
polygon-mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}" # 80001 # legacy
# ... (other endpoints as previously written)


############################################################
# non-forge settings, but necessary for deploy.py
############################################################
[chain_ids]
mainnet = "1"
goerli = "5"
optimism = "10"
optimism-goerli = "420"
arbitrum = "42161"
polygon = "137"
polygon-mumbai = "80001"
# ... (other chain IDs)

[legacy]
polygon = true
polygon-mumbai = true
# ... (legacy settings)
############################################################

[etherscan]
mainnet = { key = "${ETHERSCAN_TOKEN}" }
goerli = { key = "${ETHERSCAN_TOKEN}" }
polygon = { key = "${POLYGONSCAN_TOKEN}" }
polygon-mumbai = { key = "${POLYGONSCAN_TOKEN}" }
# ... (other etherscan settings)
